# Generated by Django 6.0.3 on 2026-03-21 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={"verbose_name": "Company", "verbose_name_plural": "Companies"},
        ),
        migrations.AlterModelOptions(
            name="customuser",
            options={"verbose_name": "User", "verbose_name_plural": "Users"},
        ),
        migrations.AlterModelOptions(
            name="department",
            options={
                "verbose_name": "Department",
                "verbose_name_plural": "Departments",
            },
        ),
        migrations.AlterModelOptions(
            name="jobtitle",
            options={"verbose_name": "Job Title", "verbose_name_plural": "Job Titles"},
        ),
        migrations.AlterModelOptions(
            name="permissiongroup",
            options={
                "verbose_name": "Permission Group",
                "verbose_name_plural": "Permission Groups",
            },
        ),
        migrations.AlterModelOptions(
            name="roletemplate",
            options={
                "verbose_name": "Role Template",
                "verbose_name_plural": "Role Templates",
            },
        ),
    ]
