# Generated by Django 6.0.3 on 2026-03-22 10:06

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_company_options_alter_customuser_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Upload an image for the content.",
                null=True,
                upload_to=core.models.base_image_path,
                validators=[core.models.validate_image_extension],
                verbose_name="Image",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="Enter a slug for the content.",
                null=True,
                verbose_name="Slug",
            ),
        ),
    ]
