# Generated by Django 6.0.3 on 2026-03-22 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_notification_notificationrecipient"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="alert",
            field=models.BooleanField(default=False),
        ),
    ]
