# Generated by Django 6.0.3 on 2026-03-17 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hotel_code",
                    models.CharField(
                        help_text="Unique property code in multi-property operations.",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "resort_code",
                    models.CharField(
                        help_text="Unique property code in multi-property operations.",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=150)),
                (
                    "begin_date",
                    models.DateField(
                        blank=True,
                        help_text="Date the property becomes active.",
                        null=True,
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="Date the property is no longer active.",
                        null=True,
                    ),
                ),
                (
                    "chain_mode",
                    models.CharField(
                        blank=True, help_text="Read-only chain mode.", max_length=50
                    ),
                ),
                (
                    "country_mode",
                    models.CharField(
                        blank=True,
                        help_text="Country-specific business logic mode.",
                        max_length=50,
                    ),
                ),
                ("currency", models.CharField(blank=True, max_length=10)),
                ("currency_format", models.CharField(blank=True, max_length=50)),
                ("catering_currency", models.CharField(blank=True, max_length=10)),
                (
                    "catering_currency_format",
                    models.CharField(blank=True, max_length=50),
                ),
                ("short_date_format", models.CharField(blank=True, max_length=30)),
                ("long_date_format", models.CharField(blank=True, max_length=50)),
                ("time_format", models.CharField(blank=True, max_length=30)),
                ("time_zone", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["hotel_code"],
            },
        ),
    ]
