# Generated by Django 6.0.3 on 2026-03-21 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0002_userpropertyaccess"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserPropertyAccess",
        ),
    ]
