# Generated by Django 6.0.3 on 2026-03-21 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0003_delete_userpropertyaccess"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
