# Generated by Django 6.0.3 on 2026-03-25 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0004_property_is_active"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="property",
            options={
                "ordering": ["hotel_code"],
                "verbose_name": "Property",
                "verbose_name_plural": "Properties",
            },
        ),
    ]
