# Generated by Django 6.0.3 on 2026-03-21 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mappings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detailsegment",
            name="description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="segment",
            name="description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="segmentgroup",
            name="description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="subsegment",
            name="description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
