# Generated by Django 6.0.3 on 2026-03-24 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("properties", "0004_property_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="SegmentGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("code", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="segment_groups",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "db_table": "segment_group",
                "ordering": ["property__resort_code", "sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="SegmentCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("code", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="segment_categories",
                        to="properties.property",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="settings.segmentgroup",
                    ),
                ),
            ],
            options={
                "db_table": "segment_category",
                "ordering": [
                    "property__resort_code",
                    "group__sort_order",
                    "sort_order",
                    "name",
                ],
            },
        ),
        migrations.CreateModel(
            name="Segment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("code", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="segments",
                        to="properties.property",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="segments",
                        to="settings.segmentcategory",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="segments",
                        to="settings.segmentgroup",
                    ),
                ),
            ],
            options={
                "db_table": "segment",
                "ordering": [
                    "property__resort_code",
                    "group__sort_order",
                    "category__sort_order",
                    "sort_order",
                    "name",
                ],
            },
        ),
        migrations.CreateModel(
            name="SegmentDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("code", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="segment_details",
                        to="properties.property",
                    ),
                ),
                (
                    "segment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="details",
                        to="settings.segment",
                    ),
                ),
            ],
            options={
                "db_table": "segment_detail",
                "ordering": ["property__resort_code", "sort_order", "name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("property", "code"),
                        name="uniq_segment_detail_property_code",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="segmentgroup",
            constraint=models.UniqueConstraint(
                fields=("property", "code"), name="uniq_segment_group_property_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="segmentcategory",
            constraint=models.UniqueConstraint(
                fields=("property", "code"), name="uniq_segment_category_property_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="segment",
            constraint=models.UniqueConstraint(
                fields=("property", "code"), name="uniq_segment_property_code"
            ),
        ),
    ]
