# Generated by Django 6.0.3 on 2026-03-25 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0005_alter_property_options"),
        ("settings", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="segmentcategory",
            options={
                "ordering": [
                    "property__resort_code",
                    "group__sort_order",
                    "sort_order",
                    "name",
                ],
                "verbose_name": "Segment Category",
                "verbose_name_plural": "Segment Categories",
            },
        ),
        migrations.CreateModel(
            name="SettingsMenu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "key",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="reports/images/"
                    ),
                ),
                ("icon", models.CharField(blank=True, max_length=100, null=True)),
                ("color", models.CharField(blank=True, max_length=100, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "allowed_properties",
                    models.ManyToManyField(
                        blank=True,
                        related_name="setting_menues",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "verbose_name": "Settings Menu",
                "verbose_name_plural": "Settings Menues",
                "ordering": ["sort_order", "title"],
            },
        ),
    ]
