# Generated by Django 6.0.3 on 2026-03-23 09:51

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("properties", "0004_property_is_active"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FileDomain",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=150, unique=True)),
                ("code", models.CharField(db_index=True, max_length=50, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("icon", models.CharField(blank=True, max_length=100, null=True)),
                ("color", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SFTPServer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=150, unique=True)),
                ("host", models.CharField(max_length=255)),
                ("port", models.PositiveIntegerField(default=22)),
                ("username", models.CharField(max_length=255)),
                ("password", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "private_key_path",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("base_path", models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="FileLoadBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("run_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("success", "Success"),
                            ("partial", "Partial"),
                            ("failed", "Failed"),
                        ],
                        default="running",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("total_files", models.PositiveIntegerField(default=0)),
                ("loaded_files", models.PositiveIntegerField(default=0)),
                ("failed_files", models.PositiveIntegerField(default=0)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "domain",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="file_load_batches",
                        to="data.filedomain",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="file_load_batches",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="FileRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "expected_filename_pattern",
                    models.CharField(
                        help_text="Example: revenue_{date}.csv or regex pattern",
                        max_length=255,
                    ),
                ),
                (
                    "file_extension",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("ad_hoc", "Ad Hoc"),
                        ],
                        default="daily",
                        max_length=20,
                    ),
                ),
                ("expected_by_time", models.TimeField(blank=True, null=True)),
                ("delimiter", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "encoding",
                    models.CharField(
                        blank=True, default="utf-8", max_length=50, null=True
                    ),
                ),
                ("is_required", models.BooleanField(default=True)),
                (
                    "domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="file_rules",
                        to="data.filedomain",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="file_rules",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "ordering": ["property", "domain", "name"],
            },
        ),
        migrations.CreateModel(
            name="IncomingFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("file_name", models.CharField(db_index=True, max_length=255)),
                ("file_path", models.CharField(max_length=1000)),
                (
                    "file_date",
                    models.DateField(
                        blank=True,
                        help_text="Business date inferred from file or folder",
                        null=True,
                    ),
                ),
                ("file_size", models.BigIntegerField(blank=True, null=True)),
                ("checksum", models.CharField(blank=True, max_length=255, null=True)),
                ("modified_at_source", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("discovered", "Discovered"),
                            ("downloaded", "Downloaded"),
                            ("validated", "Validated"),
                            ("loaded", "Loaded"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                            ("missing", "Missing"),
                        ],
                        default="discovered",
                        max_length=20,
                    ),
                ),
                ("load_message", models.TextField(blank=True, null=True)),
                ("loaded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "domain",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incoming_files",
                        to="data.filedomain",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_files",
                        to="properties.property",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incoming_files",
                        to="data.filerule",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FileLoadLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("discover", "Discover"),
                            ("download", "Download"),
                            ("validate", "Validate"),
                            ("load", "Load"),
                            ("fail", "Fail"),
                            ("retry", "Retry"),
                            ("manual_update", "Manual Update"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.TextField(blank=True, null=True)),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs",
                        to="data.fileloadbatch",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="file_load_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "incoming_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="data.incomingfile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExpectedFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("expected_date", models.DateField()),
                ("is_found", models.BooleanField(default=False)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="properties.property",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expected_files",
                        to="data.filerule",
                    ),
                ),
                (
                    "incoming_file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="data.incomingfile",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PropertySFTPSource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("source_name", models.CharField(max_length=150)),
                ("remote_path", models.CharField(max_length=500)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_sources",
                        to="properties.property",
                    ),
                ),
                (
                    "server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="property_sources",
                        to="data.sftpserver",
                    ),
                ),
            ],
            options={
                "ordering": ["property", "source_name"],
            },
        ),
        migrations.AddField(
            model_name="incomingfile",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="incoming_files",
                to="data.propertysftpsource",
            ),
        ),
        migrations.AddField(
            model_name="filerule",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="file_rules",
                to="data.propertysftpsource",
            ),
        ),
        migrations.AddField(
            model_name="fileloadbatch",
            name="source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="file_load_batches",
                to="data.propertysftpsource",
            ),
        ),
        migrations.AddIndex(
            model_name="incomingfile",
            index=models.Index(
                fields=["property", "file_name"], name="data_incomi_propert_78cf18_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="incomingfile",
            index=models.Index(
                fields=["property", "file_date"], name="data_incomi_propert_b7d00c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="incomingfile",
            index=models.Index(fields=["status"], name="data_incomi_status_f33421_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="incomingfile",
            unique_together={("source", "file_path")},
        ),
        migrations.AlterUniqueTogether(
            name="filerule",
            unique_together={("property", "source", "domain", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="propertysftpsource",
            unique_together={("property", "server", "source_name", "remote_path")},
        ),
    ]
