# Generated by Django 6.0.3 on 2026-03-24 08:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0001_initial"),
        ("properties", "0004_property_is_active"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="expectedfile",
            options={"ordering": ["-expected_date", "rule__name"]},
        ),
        migrations.AlterUniqueTogether(
            name="filerule",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="incomingfile",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="propertysftpsource",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="expectedfile",
            name="expected_filename",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="expectedfile",
            name="found_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="expectedfile",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="expectedfile",
            name="source",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expected_files",
                to="data.propertysftpsource",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="expectedfile",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("found", "Found"),
                    ("missing", "Missing"),
                    ("late", "Late"),
                    ("skipped", "Skipped"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="filerule",
            name="date_source",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("filename", "Filename"),
                    ("folder", "Folder"),
                    ("forced", "Forced"),
                ],
                default="none",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="filerule",
            name="filename_date_regex",
            field=models.CharField(
                blank=True,
                help_text="Regex for filename date. Example: (?P<date>\\d{8})",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="filerule",
            name="folder_date_regex",
            field=models.CharField(
                blank=True,
                help_text="Regex for folder date. Example: (?P<date>\\d{4}-\\d{2}-\\d{2})",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="filerule",
            name="hash_type",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("md5", "MD5"),
                    ("sha1", "SHA1"),
                    ("sha256", "SHA256"),
                ],
                default="none",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="filerule",
            name="match_type",
            field=models.CharField(
                choices=[
                    ("contains", "Contains"),
                    ("startswith", "Starts With"),
                    ("exact", "Exact"),
                    ("regex", "Regex"),
                ],
                default="contains",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="filerule",
            name="max_file_size",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="filerule",
            name="max_scan_depth",
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name="filerule",
            name="min_file_size",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="filerule",
            name="recursive_scan",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="incomingfile",
            name="checksum_type",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="incomingfile",
            name="folder_path",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="expectedfile",
            name="incoming_file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="expected_matches",
                to="data.incomingfile",
            ),
        ),
        migrations.AlterField(
            model_name="expectedfile",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expected_files",
                to="properties.property",
            ),
        ),
        migrations.AlterField(
            model_name="fileloadbatch",
            name="run_date",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name="filerule",
            name="expected_filename_pattern",
            field=models.CharField(
                help_text="Plain text or regex depending on match_type.", max_length=500
            ),
        ),
        migrations.AlterField(
            model_name="incomingfile",
            name="checksum",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="incomingfile",
            name="file_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="expectedfile",
            index=models.Index(
                fields=["property", "expected_date"],
                name="data_expect_propert_5fcfe5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="expectedfile",
            index=models.Index(fields=["status"], name="data_expect_status_3a5a7f_idx"),
        ),
        migrations.AddIndex(
            model_name="incomingfile",
            index=models.Index(
                fields=["rule", "file_date"], name="data_incomi_rule_id_2dcde5_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="expectedfile",
            constraint=models.UniqueConstraint(
                fields=("rule", "expected_date"),
                name="uniq_expected_file_per_rule_date",
            ),
        ),
        migrations.AddConstraint(
            model_name="filerule",
            constraint=models.UniqueConstraint(
                fields=("property", "source", "domain", "name"),
                name="uniq_file_rule_per_property_source_domain_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="incomingfile",
            constraint=models.UniqueConstraint(
                fields=("source", "file_path"),
                name="uniq_incoming_file_per_source_path",
            ),
        ),
        migrations.AddConstraint(
            model_name="propertysftpsource",
            constraint=models.UniqueConstraint(
                fields=("property", "server", "source_name", "remote_path"),
                name="uniq_property_server_source_remote_path",
            ),
        ),
    ]
