# Generated by Django 5.0.1 on 2024-04-05 22:33

import django.db.models.deletion
import parler.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articletranslation',
            name='description',
            field=models.TextField(blank=True, help_text='Enter a description for the content.', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='articletranslation',
            name='name',
            field=models.CharField(blank=True, help_text='Enter a name for the content.', max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='articletranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='blogs.article'),
        ),
    ]
