# Generated by Django 5.0.1 on 2024-04-05 23:01

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_alter_article_options_alter_bloguser_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='BlogCategory',
        ),
        migrations.RenameModel(
            old_name='TagTranslation',
            new_name='BlogCategoryTranslation',
        ),
        migrations.RenameModel(
            old_name='Tag',
            new_name='BlogTag',
        ),
        migrations.RenameModel(
            old_name='CategoryTranslation',
            new_name='BlogTagTranslation',
        ),
        migrations.AlterModelOptions(
            name='blogcategorytranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'blog category Translation'},
        ),
        migrations.AlterModelOptions(
            name='blogtagtranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'blog tag Translation'},
        ),
        migrations.AlterModelTable(
            name='blogcategorytranslation',
            table='blogs_blogcategory_translation',
        ),
        migrations.AlterModelTable(
            name='blogtagtranslation',
            table='blogs_blogtag_translation',
        ),
        migrations.CreateModel(
            name='BlogImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Upload an image for the articles.', null=True, upload_to=core.models.base_image_path, validators=[core.models.validate_image_extension], verbose_name='Image')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_images', to='blogs.article')),
            ],
        ),
    ]
