# Generated by Django 4.2.11 on 2024-04-06 21:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogs', '0005_alter_blogcategorytranslation_master_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='Post',
        ),
        migrations.RenameModel(
            old_name='ArticleTranslation',
            new_name='PostTranslation',
        ),
        migrations.AlterModelOptions(
            name='blogcategory',
            options={'verbose_name': 'Blog Category', 'verbose_name_plural': 'Blog Categories'},
        ),
        migrations.AlterModelOptions(
            name='blogcategorytranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Blog Category Translation'},
        ),
        migrations.AlterModelOptions(
            name='posttranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'post Translation'},
        ),
        migrations.AlterModelTable(
            name='posttranslation',
            table='blogs_post_translation',
        ),
    ]
