# Generated by Django 4.2.11 on 2024-04-06 21:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_rename_article_post_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name_plural': 'Posts'},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='created_by',
            new_name='author',
        ),
        migrations.AlterField(
            model_name='post',
            name='publish_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
