# Generated by Django 4.2.11 on 2024-04-07 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_post_read_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='read_time',
        ),
        migrations.AddField(
            model_name='posttranslation',
            name='read_time',
            field=models.IntegerField(default=0),
        ),
    ]
