# Generated by Django 4.2.11 on 2024-04-14 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_remove_post_read_time_posttranslation_read_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogimage',
            old_name='product',
            new_name='post',
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(related_name='post', to='blogs.blogtag'),
        ),
    ]
