# Generated by Django 4.2.11 on 2024-04-14 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0010_rename_product_blogimage_post_alter_post_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogimage',
            old_name='post',
            new_name='post_images',
        ),
    ]
