# Generated by Django 4.2.11 on 2024-04-14 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0011_rename_post_blogimage_post_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogimage',
            old_name='post_images',
            new_name='post',
        ),
    ]
