# Generated by Django 4.2.11 on 2024-04-14 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0013_alter_blogimage_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogimage',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_images', to='blogs.post'),
        ),
    ]
