# Generated by Django 4.2.11 on 2024-04-16 09:06

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0014_alter_blogimage_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-created',), 'verbose_name_plural': 'Posts'},
        ),
        migrations.AlterField(
            model_name='posttranslation',
            name='file_html',
            field=models.FileField(blank=True, upload_to=core.models.custom_upload_path),
        ),
        migrations.AlterField(
            model_name='posttranslation',
            name='file_markdown',
            field=models.FileField(blank=True, upload_to=core.models.custom_upload_path),
        ),
    ]
