# Generated by Django 4.2.11 on 2024-04-16 09:18

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0015_alter_post_options_alter_posttranslation_file_html_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posttranslation',
            name='file_html',
            field=models.FileField(blank=True, upload_to=core.models.custom_upload_path_html),
        ),
        migrations.AlterField(
            model_name='posttranslation',
            name='file_markdown',
            field=models.FileField(blank=True, upload_to=core.models.custom_upload_path_rm),
        ),
    ]
