# Generated by Django 4.2.11 on 2024-04-18 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0017_alter_posttranslation_file_html_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcategory',
            name='created_by',
        ),
    ]
