# Generated by Django 6.0.3 on 2026-03-21 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0001_initial"),
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="reportgroupaccess",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="reportgroupaccess",
            name="group",
        ),
        migrations.RemoveField(
            model_name="reportgroupaccess",
            name="property",
        ),
        migrations.AddField(
            model_name="report",
            name="allowed_properties",
            field=models.ManyToManyField(
                blank=True, related_name="reports", to="properties.property"
            ),
        ),
        migrations.AddField(
            model_name="reportgroup",
            name="allowed_properties",
            field=models.ManyToManyField(
                blank=True, related_name="report_groups", to="properties.property"
            ),
        ),
        migrations.DeleteModel(
            name="ReportAccess",
        ),
        migrations.DeleteModel(
            name="ReportGroupAccess",
        ),
    ]
