# Generated by Django 6.0.3 on 2026-03-21 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0002_alter_reportgroupaccess_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="color",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="reportgroup",
            name="color",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
