# Generated by Django 5.0.1 on 2024-03-14 21:50

import core.models
import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offering',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='homepage.siteinformation'),
        ),
        migrations.AlterField(
            model_name='sitemetadata',
            name='logo',
            field=models.ImageField(blank=True, help_text='Upload Logo image.', null=True, upload_to='home/', validators=[core.models.validate_image_extension], verbose_name='Logo'),
        ),
        migrations.CreateModel(
            name='Framework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, help_text='Enter a slug for the content.', null=True, unique=True, verbose_name='Slug')),
                ('image', models.ImageField(blank=True, help_text='Upload an image for the content.', null=True, upload_to=core.models.base_image_path, validators=[core.models.validate_image_extension], verbose_name='Image')),
                ('icon', models.CharField(blank=True, help_text='Enter an icon for the content.', max_length=100, null=True, verbose_name='Icon')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The date and time when the content was created.', verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, help_text='The date and time when the content was last modified.', verbose_name='Modified')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frameworks', to='homepage.siteinformation')),
            ],
            options={
                'ordering': ['-modified'],
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FrameworkTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(blank=True, help_text='Enter a name for the content.', max_length=100, null=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, help_text='Enter a description for the content.', null=True, verbose_name='Description')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='homepage.framework')),
            ],
            options={
                'verbose_name': 'framework Translation',
                'db_table': 'homepage_framework_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
