# Generated by Django 5.0.1 on 2024-03-15 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_alter_offering_site_alter_sitemetadata_logo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitemetadata',
            old_name='facebook_url',
            new_name='facebook',
        ),
        migrations.RenameField(
            model_name='sitemetadata',
            old_name='googlemap_url',
            new_name='github',
        ),
        migrations.RenameField(
            model_name='sitemetadata',
            old_name='instagram_url',
            new_name='googlemap',
        ),
        migrations.RenameField(
            model_name='sitemetadata',
            old_name='linkedin_url',
            new_name='instagram',
        ),
        migrations.RenameField(
            model_name='sitemetadata',
            old_name='twitter_url',
            new_name='linkedin',
        ),
        migrations.RenameField(
            model_name='sitemetadata',
            old_name='whatsapp_url',
            new_name='medium',
        ),
        migrations.AddField(
            model_name='sitemetadata',
            name='other_social',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitemetadata',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitemetadata',
            name='whatsapp',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitemetadata',
            name='youtube',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businesscategory',
            name='slug',
            field=models.SlugField(blank=True, help_text='Enter a slug for the content.', null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='slug',
            field=models.SlugField(blank=True, help_text='Enter a slug for the content.', null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='framework',
            name='slug',
            field=models.SlugField(blank=True, help_text='Enter a slug for the content.', null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='marketing',
            name='slug',
            field=models.SlugField(blank=True, help_text='Enter a slug for the content.', null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='offering',
            name='slug',
            field=models.SlugField(blank=True, help_text='Enter a slug for the content.', null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, help_text='Enter a slug for the content.', null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, help_text='Enter a slug for the content.', null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='slug',
            field=models.SlugField(blank=True, help_text='Enter a slug for the content.', null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='slug',
            field=models.SlugField(blank=True, help_text='Enter a slug for the content.', null=True, verbose_name='Slug'),
        ),
    ]
