# Generated by Django 5.0.1 on 2024-03-15 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_rename_facebook_url_sitemetadata_facebook_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitemetadata',
            old_name='twitter',
            new_name='xtwitter',
        ),
        migrations.RenameField(
            model_name='teammember',
            old_name='twitter',
            new_name='xtwitter',
        ),
    ]
