# Generated by Django 5.0.1 on 2024-03-15 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_rename_twitter_sitemetadata_xtwitter_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitemetadata',
            old_name='xtwitter',
            new_name='twitter',
        ),
        migrations.RenameField(
            model_name='teammember',
            old_name='xtwitter',
            new_name='twitter',
        ),
    ]
