# Generated by Django 5.0.1 on 2024-03-15 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_businesscategory_is_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinformation',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='siteinformation',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
