# Generated by Django 5.0.1 on 2024-03-15 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_alter_businesscategory_is_available_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businesscategory',
            old_name='is_available',
            new_name='is_published',
        ),
        migrations.RenameField(
            model_name='feature',
            old_name='is_available',
            new_name='is_published',
        ),
        migrations.RenameField(
            model_name='framework',
            old_name='is_available',
            new_name='is_published',
        ),
        migrations.RenameField(
            model_name='marketing',
            old_name='is_available',
            new_name='is_published',
        ),
        migrations.RenameField(
            model_name='offering',
            old_name='is_available',
            new_name='is_published',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='is_available',
            new_name='is_published',
        ),
        migrations.RenameField(
            model_name='siteinformation',
            old_name='is_available',
            new_name='is_published',
        ),
        migrations.RenameField(
            model_name='teammember',
            old_name='is_available',
            new_name='is_published',
        ),
        migrations.RenameField(
            model_name='testimonial',
            old_name='is_available',
            new_name='is_published',
        ),
        migrations.RemoveField(
            model_name='project',
            name='is_available',
        ),
        migrations.AlterField(
            model_name='project',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
