# Generated by Django 6.0.3 on 2026-03-21 23:31

import core.models
import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0009_rename_is_available_businesscategory_is_published_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="Enter a slug for the content.",
                        null=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Upload an image for the content.",
                        null=True,
                        upload_to=core.models.base_image_path,
                        validators=[core.models.validate_image_extension],
                        verbose_name="Image",
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("is_published", models.BooleanField(default=True)),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="The date and time when the content was created.",
                        verbose_name="Created",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date and time when the content was last modified.",
                        verbose_name="Modified",
                    ),
                ),
                (
                    "url",
                    models.CharField(
                        blank=True,
                        help_text="Direct URL or anchor like /en/#services",
                        max_length=300,
                        null=True,
                        verbose_name="URL",
                    ),
                ),
                (
                    "route_name",
                    models.CharField(
                        blank=True,
                        help_text="Optional Django route name like home or service-detail",
                        max_length=100,
                        null=True,
                        verbose_name="Route Name",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="FontAwesome icon class.",
                        max_length=100,
                        null=True,
                        verbose_name="Icon",
                    ),
                ),
                (
                    "anchor",
                    models.CharField(
                        blank=True,
                        help_text="Optional anchor like services or projects",
                        max_length=100,
                        null=True,
                        verbose_name="Anchor",
                    ),
                ),
                ("open_in_new_tab", models.BooleanField(default=False)),
                ("is_dropdown", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="homepage.menuitem",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menu_items",
                        to="homepage.siteinformation",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "-modified"],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="MenuItemTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        db_index=True, max_length=15, verbose_name="Language"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Enter a name for the content.",
                        max_length=100,
                        null=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Enter a description for the content.",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="homepage.menuitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "menu item Translation",
                "db_table": "homepage_menuitem_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
