# Generated by Django 6.0.3 on 2026-03-22 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0010_menuitem_menuitemtranslation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siteinformationadditional",
            name="site",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="additional_info",
                to="homepage.siteinformation",
            ),
        ),
    ]
