# Generated by Django 6.0.3 on 2026-03-28 17:28

import core.models
import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0011_alter_siteinformationadditional_site"),
    ]

    operations = [
        migrations.CreateModel(
            name="PricingPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="Enter a slug for the content.",
                        null=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Upload an image for the content.",
                        null=True,
                        upload_to=core.models.base_image_path,
                        validators=[core.models.validate_image_extension],
                        verbose_name="Image",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Enter an icon for the content.",
                        max_length=100,
                        null=True,
                        verbose_name="Icon",
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("is_published", models.BooleanField(default=True)),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="The date and time when the content was created.",
                        verbose_name="Created",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date and time when the content was last modified.",
                        verbose_name="Modified",
                    ),
                ),
                (
                    "billing_interval",
                    models.CharField(
                        choices=[
                            ("free", "Free"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("yearly", "Yearly"),
                            ("one_time", "One Time"),
                            ("custom", "Custom"),
                        ],
                        default="monthly",
                        max_length=20,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("USD", "USD"),
                            ("EUR", "EUR"),
                            ("GBP", "GBP"),
                            ("AED", "AED"),
                            ("SAR", "SAR"),
                        ],
                        default="USD",
                        max_length=10,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Leave empty for Contact Us / Custom pricing",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "compare_at_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Optional old price for discounts",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("trial_days", models.PositiveIntegerField(default=0)),
                (
                    "setup_fee",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("is_free", models.BooleanField(default=False)),
                (
                    "is_custom_price",
                    models.BooleanField(
                        default=False,
                        help_text="Enable for enterprise or contact-sales plans",
                    ),
                ),
                ("allow_subscribe", models.BooleanField(default=True)),
                ("allow_contact_sales", models.BooleanField(default=False)),
                ("sort_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Pricing Plan",
                "verbose_name_plural": "Pricing Plans",
                "ordering": ["sort_order", "id"],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="PricingFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="Enter a slug for the content.",
                        null=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Upload an image for the content.",
                        null=True,
                        upload_to=core.models.base_image_path,
                        validators=[core.models.validate_image_extension],
                        verbose_name="Image",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Enter an icon for the content.",
                        max_length=100,
                        null=True,
                        verbose_name="Icon",
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("is_published", models.BooleanField(default=True)),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="The date and time when the content was created.",
                        verbose_name="Created",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date and time when the content was last modified.",
                        verbose_name="Modified",
                    ),
                ),
                (
                    "value_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("boolean", "Boolean"),
                            ("number", "Number"),
                        ],
                        default="boolean",
                        max_length=20,
                    ),
                ),
                ("value_boolean", models.BooleanField(default=True)),
                (
                    "value_number",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="features",
                        to="homepage.pricingplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pricing Feature",
                "verbose_name_plural": "Pricing Features",
                "ordering": ["sort_order", "id"],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="PricingPlanLimit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="Enter a slug for the content.",
                        null=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Upload an image for the content.",
                        null=True,
                        upload_to=core.models.base_image_path,
                        validators=[core.models.validate_image_extension],
                        verbose_name="Image",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Enter an icon for the content.",
                        max_length=100,
                        null=True,
                        verbose_name="Icon",
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("is_published", models.BooleanField(default=True)),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="The date and time when the content was created.",
                        verbose_name="Created",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date and time when the content was last modified.",
                        verbose_name="Modified",
                    ),
                ),
                (
                    "limit_type",
                    models.CharField(
                        choices=[
                            ("integer", "Integer"),
                            ("decimal", "Decimal"),
                            ("unlimited", "Unlimited"),
                            ("custom", "Custom"),
                        ],
                        default="integer",
                        max_length=20,
                    ),
                ),
                ("value_integer", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "value_decimal",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="limits",
                        to="homepage.pricingplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pricing Plan Limit",
                "verbose_name_plural": "Pricing Plan Limits",
                "ordering": ["sort_order", "id"],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="PricingSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="Enter a slug for the content.",
                        null=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Upload an image for the content.",
                        null=True,
                        upload_to=core.models.base_image_path,
                        validators=[core.models.validate_image_extension],
                        verbose_name="Image",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Enter an icon for the content.",
                        max_length=100,
                        null=True,
                        verbose_name="Icon",
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("is_published", models.BooleanField(default=True)),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="The date and time when the content was created.",
                        verbose_name="Created",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date and time when the content was last modified.",
                        verbose_name="Modified",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pricing_sections",
                        to="homepage.siteinformation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pricing Section",
                "verbose_name_plural": "Pricing Sections",
                "ordering": ["-created"],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name="pricingplan",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plans",
                to="homepage.pricingsection",
            ),
        ),
        migrations.CreateModel(
            name="PricingFeatureTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        db_index=True, max_length=15, verbose_name="Language"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "description",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                ("value_text", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="homepage.pricingfeature",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pricing Feature Translation",
                "db_table": "homepage_pricingfeature_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="PricingPlanLimitTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        db_index=True, max_length=15, verbose_name="Language"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("unit", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "custom_value",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="homepage.pricingplanlimit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pricing Plan Limit Translation",
                "db_table": "homepage_pricingplanlimit_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="PricingPlanTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        db_index=True, max_length=15, verbose_name="Language"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "short_description",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("badge_text", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "price_label",
                    models.CharField(
                        blank=True,
                        help_text="Examples: Per Month, Per User / Month, Contact Us",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "button_text",
                    models.CharField(default="Get Started", max_length=100),
                ),
                ("button_url", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="homepage.pricingplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pricing Plan Translation",
                "db_table": "homepage_pricingplan_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="PricingSectionTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        db_index=True, max_length=15, verbose_name="Language"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Enter a name for the content.",
                        max_length=100,
                        null=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Enter a description for the content.",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="homepage.pricingsection",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pricing Section Translation",
                "db_table": "homepage_pricingsection_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
