# Generated by Django 6.0.3 on 2026-03-28 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0012_pricingplan_pricingfeature_pricingplanlimit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pricingplan",
            name="is_popular",
            field=models.BooleanField(default=False),
        ),
    ]
