# Generated by Django 6.0.3 on 2026-03-29 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0013_pricingplan_is_popular"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteinformation",
            name="slogan",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
