TRX_CODES = [
    'TRX_CODE',
    'DESCRIPTION',
    'TAX_INCLUSIVE_YN',
    'TRX_CODE_TYPE',
]

TRX_CODE_TAX = [
    'TRX_CODE_GENERATOR',
    'TRX_CODE',
    'TCR_TYPE',
    'AMOUNT',
    'PERCENTAGE',
    'PERCENTAGE_BASE_CODE',
    'UDF_FUNCTION',
    'RESULT_INCLUDED_IN_SUM_ARRAY',
    'CALCULATION_SEQUENCE',
    'TC_GROUP_GENERATOR',
    'AMOUNT_FROM_SCHEDULE_YN',
    'TC_GROUP',
    'TC_SUBGROUP',
    'TC_SUBGROUP_GENERATOR',
]

TRX_CODE_TAXTYPE = [
    'START_DATE',
    'NAME_TAX_TYPE',
    'AMOUNT',
    'PERCENTAGE',
    'PERCENTAGE_BASE_CODE',
    'UDF_FUNCTION',
    'TC_GROUP',
    'CURRENCY',
    'TC_SUBGROUP',
]

RATE_CODES = [
    'RATE_CODE',
    'RATE_CATEGORY',
    'CURRENCY_CODE',
    'TRX_CODE',
    'COMPLIMENTARY_YN',
    'HOUSE_USE_YN',
]

ROOM_TYPES = [
    'ROOM_CATEGORY',
    'LABEL',
    'ROOM_CLASS',
    'SHORT_DESCRIPTION',
    'PSEUDO_ROOM_TYPE',
    'NUMBER_ROOMS',
    'MAX_OCCUPANCY',
    'SUITE_YN',
]

ROOM_CAT_COMBINATIONS = [
    'COMBINATION_ROOM_CATEGORY',
    'COMPONENT_ROOM_CATEGORY',
    'QUANTITY',
]

MARKET_CODES = [
    'MARKET_CODE',
    'DESCRIPTION',
    'PARENT_MARKET_CODE',
]

SOURCE_CODES = [
    'SOURCE_CODE',
    'DESCRIPTION',
    'PARENT_SOURCE_CODE',
]

PACKAGES = [
    'PRODUCT',
    'CURRENCY_CODE',
    'CALCULATION_RULE',
    'PRINT_SEPARATE_YN',
    'ADD_TO_RATE_YN',
    'DEPT_CODE',
    'DEPT_TAX_FLAG',
    'FORECAST_NEXT_DAY_YN',
]

PMS_APPLICATION_PARAMETERS = [
    'PARAMETER_NAME',
    'PARAMETER_VALUE',
    'PARAMETER_GROUP',
    'PARAMETER_TYPE',
]

RATE_ROOM_TRX = [
    'RATE_CODE',
    'ENTITY_TYPE',
    'ENTITY_VALUE',
    'TRX_CODE',
]

CHANNEL_CODES = [
    'ATTRIBUTE_CODE',
    'DESCRIPTION',
]

PMS_VERSIONS = [
    'VERSION',
    'EPATCHLEVEL',
    'INSTALLED_DATE',
]

PROPERTY_DEF = [
    'RESORT',
    'BEGIN_DATE',
    'NAME',
    'LEGAL_OWNER',
    'COUNTRY_CODE',
    'POST_CODE',
    'CITY',
    'STATE',
    'INSERT_DATE',
    'UPDATE_DATE',
    'CHAIN_CODE',
    'RESORT_TYPE',
    'CRO_CODE',
]