# Generated by Django 6.0.3 on 2026-03-29 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="user_agent",
            field=models.TextField(blank=True, null=True),
        ),
    ]
